db:
#    image: mariadb:latest
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=agilefant
    - MYSQL_USER=agilefant
    - MYSQL_PASSWORD=agilefant

app:
    image: edward8628/agilefant:latest
    ports:
        - "8080:8080"
    links:
        - "db:db"